---
kind: Service
apiVersion: v1
metadata:
    name: welcomeservice
spec:
    selector:
        app: welcome
    ports:
        - protocol: "TCP"
              # the port to forward traffic to inside the pod
          targetPort: 8080
              # port to access the cluster
          nodePort: 30002
              # port to access from inside the cluster
          port: 8081
    type: LoadBalancer
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: welcome-deployment #name of the deployment
spec:
    minReadySeconds: 5
    replicas: 5 # five container that should run in our desired state
    selector:
        matchLabels:
            app: welcome
    template:
        metadata:
            labels:
                app: welcome
        spec:
            containers:
                - name: welcome-container
                  image: jenskaras/welcome:v1
                  ports:
                  - containerPort: 8080
                    protocol: TCP
 

