---
kind: Service
apiVersion: v1
metadata:
    name: calcservice #use this to talk to the calc application
spec:
    selector:
         app: calc
    ports:
        - protocol: "TCP" 
          targetPort: 8080 # the port to forward traffic to inside the pod
          port: 8080 # port to access from inside the cluster
    type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: calc-deployment #name of the deployment
spec:
    minReadySeconds: 5
    replicas: 3 # five container that should run in our desired state
    selector:
        matchLabels:
            app: calc
    template:
        metadata:
            labels:
                app: calc
        spec:
            imagePullSecrets:
            #kubectl create secret docker-registry <name> --docker-server=DOCKER_REGISTRY_SERVER --docker-username=DOCKER_USER --docker-password=DOCKER_PASSWORD --docker-email=DOCKER_EMAIL
              - name: myregkey # create key via command in shel
            containers:
                - name: calc-container
                  image: jenskaras/welcome:calculatorV1
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
                        protocol: TCP
